export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const CHANGE_FILTER_OPTION = 'CHANGE_FILTER_OPTION';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';